apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy # Deployment name
  labels: # key/value pairs attached to objects, such as Pods, for organising and selecting subsets of objects
    name: postgres-deploy
    app: demo-voting-app

spec:
  replicas: 1
  
  selector:
    matchLabels: # should match pod labels in template 
      name: postgres-pod
      app: demo-voting-app

  template:
    metadata:
      name: postgres-pod # pod name
      labels: # should match Deployment matchLabels above 
        name: postgres-pod
        app: demo-voting-app

    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"