apiVersion: v1
kind: Service
metadata:
  name: db # pod name
  labels: # key/value pairs attached to objects, such as Pods, for organising and selecting subsets of objects
    name: postgres-service
    app: demo-voting-app

spec: # type, selector, ports
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod 
    app: demo-voting-app


