apiVersion: v1
kind: Service
metadata:
  name: redis # pod name
  labels: # key/value pairs attached to objects, such as Pods, for organising and selecting subsets of objects
    name: redis-service
    app: demo-voting-app

spec: # type, selector, ports
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod 
    app: demo-voting-app


